#branches:
#  except:
#    - gh-pages
language: perl6
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda installdeps .
  - panda install NCurses
  - panda install Term::termios
  - panda install Terminal::WCWidth
sudo: false
