#branches:
#  except:
#    - gh-pages
language: perl6
perl6:
  - latest
install:
  - rakudobrew build zef
  - zef --depsonly install .
  - zef install Term::termios
  - zef install Terminal::WCWidth
sudo: false
