#branches:
#  except:
#    - gh-pages
language: perl6
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda --verbose installdeps .
  - panda --verbose install NCurses
  - panda --verbose install Term::termios
  - panda --verbose install Terminal::WCWidth
sudo: false
