#branches:
#  except:
#    - gh-pages
language: perl6
perl6:
  - latest
install:
  - echo $TRAVIS_OS_NAME
  - rakudobrew build-panda
  - panda --verbose installdeps .
  - panda install Term::termios
  - panda install Terminal::WCWidth
sudo: false
